import React, { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { FaFilePdf, FaSearch, FaCalendarAlt } from 'react-icons/fa';
import api from '../services/api';

export default function Bordereaux() {
  const [searchTerm, setSearchTerm] = useState('');

  const { data: bordereaux, isLoading } = useQuery({
    queryKey: ['bordereaux'],
    queryFn: async () => {
      const res = await api.get('/bordereaux');
      return res.data;
    }
  });

  const filteredItems = (bordereaux || []).filter(item => 
    item.code.toLowerCase().includes(searchTerm.toLowerCase()) ||
    (item.deliveryMan?.name || '').toLowerCase().includes(searchTerm.toLowerCase())
  );

  const downloadPdf = (id) => {
    window.open(`${api.defaults.baseURL}/bordereaux/${id}/pdf`, '_blank');
  };

  if (isLoading) return <div className="p-8 text-center">Loading manifests...</div>;

  return (
    <div className="p-6">
      <div className="flex justify-between items-center mb-6">
        <div>
          <h1 className="text-2xl font-bold flex items-center gap-2">
            <FaFilePdf className="text-red-600" /> Delivery Manifests (Bordereaux)
          </h1>
          <p className="text-gray-500">History of generated delivery sheets</p>
        </div>
        
        <div className="relative">
          <input
            type="text"
            placeholder="Search code or agent..."
            className="pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-indigo-500 focus:border-indigo-500 w-64"
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
          />
          <FaSearch className="absolute left-3 top-3 text-gray-400" />
        </div>
      </div>

      <div className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
        <table className="w-full text-left">
          <thead className="bg-gray-50 border-b border-gray-200">
            <tr>
              <th className="px-6 py-4 font-semibold text-gray-600">Code</th>
              <th className="px-6 py-4 font-semibold text-gray-600">Date</th>
              <th className="px-6 py-4 font-semibold text-gray-600">Status</th>
              <th className="px-6 py-4 font-semibold text-gray-600">Delivery Agent</th>
              <th className="px-6 py-4 font-semibold text-gray-600 text-center">Orders</th>
              <th className="px-6 py-4 font-semibold text-gray-600">Total Amount</th>
              <th className="px-6 py-4 font-semibold text-gray-600">Generated By</th>
              <th className="px-6 py-4 font-semibold text-gray-600 text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-100">
            {filteredItems.map((item) => (
              <tr key={item._id} className="hover:bg-gray-50 transition-colors">
                <td className="px-6 py-4 font-mono font-medium text-indigo-600">
                  {item.code}
                </td>
                <td className="px-6 py-4 text-gray-600">
                  <div className="flex items-center gap-2">
                    <FaCalendarAlt className="text-gray-400" />
                    {new Date(item.createdAt).toLocaleDateString()} {new Date(item.createdAt).toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'})}
                  </div>
                </td>
                <td className="px-6 py-4">
                    <span className={`px-2 py-1 rounded-full text-xs font-bold ${item.status === 'Validé' ? 'bg-green-100 text-green-800' : 'bg-yellow-100 text-yellow-800'}`}>
                        {item.status || 'Draft'}
                    </span>
                </td>
                <td className="px-6 py-4 font-medium">
                  {item.deliveryMan?.name ? (
                      <span className="text-gray-900">{item.deliveryMan.name}</span>
                  ) : (
                      <span className="text-gray-400 italic">Unassigned</span>
                  )}
                </td>
                <td className="px-6 py-4 text-center">
                  <span className="bg-gray-100 text-gray-800 px-2 py-1 rounded-md text-sm font-bold">
                    {item.orders?.length || 0}
                  </span>
                </td>
                <td className="px-6 py-4 font-bold text-gray-800">
                  {item.totalAmount?.toFixed(2)} TND
                </td>
                <td className="px-6 py-4 text-gray-500 text-sm">
                  {item.generatedBy?.name || 'System'}
                </td>
                <td className="px-6 py-4 text-right">
                  <button 
                    onClick={() => downloadPdf(item._id)}
                    className="text-red-600 hover:text-red-800 hover:bg-red-50 p-2 rounded-full transition-colors"
                    title="Download PDF"
                  >
                    <FaFilePdf size={18} />
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
        
        {filteredItems.length === 0 && (
          <div className="p-12 text-center text-gray-500">
            No manifests found matching your search.
          </div>
        )}
      </div>
    </div>
  );
}
